chore: fix action name and reference

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,128 +1,92 @@
-name: build-layer
+name: export layer
 on:
-  workflow_call:
-    secrets:
-      token:
-        description: "GitHub token to use for authentication"
-        required: true
-    inputs:
-      package-name:
-        description: "Name of the package to create."
-        required: true
-        type: string
-      version:
-        description: "Version of the package to create."
-        required: true
-        type: string
-      registry:
-        description: "Container registry to use for publishing the package."
-        required: false
-        default: "https://registry.oomol.com"
-        type: string
+  push:
+    tags:
+      - '**'
+env:
+  registry: https://registry.oomol.com
 
 permissions:
   contents: read
   id-token: write
 
 jobs:
-  arguments-check:
+  package:
     runs-on: ubuntu-latest
+    outputs:
+      name: ${{ steps.get_name.outputs.name }}
+      version: ${{ steps.get_version.outputs.version }}
+      is-publish: ${{ steps.is_publish.outputs.result }}
     steps:
-      - name: check argument
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Get name
+        id: get_name
         run: |
-          if [ -z "${{ inputs.package-name }}" ]; then
-            echo "Error: package-name is required"
-            exit 1
-          fi
-          if [ -z "${{ inputs.version }}" ]; then
-            echo "Error: version is required"
-            exit 1
-          fi
-  export-layer:
-    strategy:
-      matrix:
-        os: [buildjet-2vcpu-ubuntu-2204, buildjet-2vcpu-ubuntu-2204-arm]
-    runs-on: ${{ matrix.os }}
-    needs: [arguments-check]
+            if [ -f package.oo.yaml ]; then
+              name=$(yq eval '.name' package.oo.yaml)
+              echo "name=$name" >> "$GITHUB_OUTPUT"
+            elif [ -f package.oo.yml ]; then
+              name=$(yq eval '.name' package.oo.yml)
+              echo "name=$name" >> "$GITHUB_OUTPUT"
+            else
+              echo "No valid package file found"
+              exit 1
+            fi
+      - name: Get version
+        id: get_version
+        run: |
+            if [ -f package.oo.yaml ]; then
+              version=$(yq eval '.version' package.oo.yaml)
+              echo "version=$version" >> "$GITHUB_OUTPUT"
+            elif [ -f package.oo.yml ]; then
+              version=$(yq eval '.version' package.oo.yml)
+              echo "version=$version" >> "$GITHUB_OUTPUT"
+            else
+              echo "No valid package file found"
+              exit 1
+            fi
+      - name: publish
+        id: is_publish
+        run: |
+            http_status=$(curl -s -o /dev/null -w "%{http_code}" "${{env.registry}}/-/oomol/detail/${{ steps.get_name.outputs.name }}/${{ steps.get_version.outputs.version }}")
+            if [ "$http_status" -eq 404 ]; then
+              echo "Package not found, proceeding to publish."
+              echo "result=false" >> "$GITHUB_OUTPUT"
+            elif [ "$http_status" -eq 200 ]; then
+              echo "Package already exists (HTTP status: $http_status), skipping publish."
+              echo "result=true" >> "$GITHUB_OUTPUT"
+            else
+              echo "Error checking package existence (HTTP status: $http_status). Assuming it doesn't exist."
+              exit 1
+            fi
+          
+  publish:
+    runs-on: ubuntu-latest
+    needs: [package]
     steps:
-      - name: architecture
-        run: |
-          echo "architecture=${{ (runner.arch == 'ARM64' || runner.arch == 'ARM') && 'arm64' || 'amd64' }}" >> $GITHUB_OUTPUT
-        id: arch
-      - uses: actions/checkout@v4
-      - uses: oomol/ovmlayer-rootfs/.github/actions/layer@main
-        with:
-          token: ${{ secrets.token }}
-          architecture: ${{ steps.arch.outputs.architecture }}
-      - name: create layer
-        run: |
-          oocana package-layer create ${{ github.workspace }}
-      - name: export layer
-        run: |
-          oocana package-layer export ${{ github.workspace }} ${{ runner.temp }}/export
-      - name: Zip layer
-        run: |
-          cd ${{ runner.temp }}/export
-          zip -r ${{ steps.arch.outputs.architecture }}-layer.zip .
-      - name: Upload layer
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ steps.arch.outputs.architecture }}-layer
-          path: ${{ runner.temp }}/export/${{ steps.arch.outputs.architecture }}-layer.zip
+      - name: Checkout code
+        uses: actions/checkout@v4
+        if: needs.package.outputs.is-publish == 'false'
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        if: needs.package.outputs.is-publish == 'false'
+      - name: Install oopm
+        run: npm install -g oopm
+        if: needs.package.outputs.is-publish == 'false'
+      - name: Publish OOMOL Package
+        uses: oomol-lab/oopm-publish-action@main
+        if: needs.package.outputs.is-publish == 'false'
 
-  upload-layer:
-    runs-on: buildjet-2vcpu-ubuntu-2204
+  export-layer:
+    needs: [package, publish]
     permissions:
       contents: read
       id-token: write
-    needs: [export-layer]
-    steps:
-      - name: download layer
-        uses: actions/download-artifact@v5
-        with:
-          path: ${{ runner.temp }}/export
-          merge-multiple: true
-      - name: Install OIDC Client from Core Package
-        run: npm install @actions/core@1.11.1 @actions/http-client
-        shell: bash
-      - name: Get Id Token
-        uses: actions/github-script@v7
-        id: id_token
-        with:
-          script: |
-            const coredemo = require('@actions/core')
-            let id_token = await coredemo.getIDToken()
-            coredemo.setOutput('id_token', id_token)
-      - name: Upload Layer 
-        run: |
-            set -x
-            cd ${{ runner.temp }}/export
-            for layer_zip in $(pwd)/*; do
-              if [ -f "$layer_zip" ]; then
-                echo "Processing $layer_zip"
-                file=$(basename $layer_zip)
-                response=$(curl --fail-with-body -X POST -H "Authorization: github-action-${{ steps.id_token.outputs.id_token }}" -H "Content-Type: application/json" -d "{\"fileKey\": \"$file\"}" ${{ inputs.registry }}/-/oomol/packages/${{ inputs.package-name }}/${{ inputs.version }}/layers/presigned-upload-url)
-                curl --fail-with-body -X PUT -H "Content-Type: application/octet-stream" -T ./$file "$response"
-              fi
-            done
-      - name: Post layer # {"key1": "file2", "key2": "file2"}
-        run: |
-          set -x
-          cd ${{ runner.temp }}/export
-          payload="{"
-          first=true
-          for layer_zip in $(pwd)/*; do
-            if [ -f "$layer_zip" ]; then
-              if [ "$first" = true ]; then
-                first=false
-              else
-                payload+=","
-              fi
-              file=$(basename "$layer_zip")
-              key=$(echo "$file" | sed 's/-layer\.zip$//')
-              payload+="\"$key\":\"$file\""
-            fi
-          done
-          payload+="}"
-          echo "Payload: $payload"
-          curl --fail-with-body -X PUT -H "Authorization: github-action-${{ steps.id_token.outputs.id_token }}" -H "Content-Type: application/json" -d "$payload" ${{ inputs.registry }}/-/oomol/packages/${{ inputs.package-name }}/${{ inputs.version }}/layers/file-paths
+
+    uses: ./.github/workflows/layer.yml@main
+    with:
+      package-name: ${{ needs.package.outputs.name }}
+      version: "${{ needs.package.outputs.version }}"
+    secrets:
+      token: ${{ secrets.GITHUB_TOKEN }}
